services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apartment-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apartment-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
